
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: devops-app
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_NAME: devopsdb
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: devops-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: devopsdb
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: devops-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ayoub.basraoui198@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8085:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
